// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/warroom-redesign/MidnightLux.tsx": () => import("../components/mockups/warroom-redesign/MidnightLux.tsx"),
  "./components/mockups/warroom-redesign/Signal.tsx": () => import("../components/mockups/warroom-redesign/Signal.tsx"),
  "./components/mockups/warroom-redesign/TacticalHUD.tsx": () => import("../components/mockups/warroom-redesign/TacticalHUD.tsx")
};
