// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/warroom-alert-redesign/AlertCommand.tsx": () => import("../components/mockups/warroom-alert-redesign/AlertCommand.tsx"),
  "./components/mockups/warroom-alert-redesign/AlertSeverityStack.tsx": () => import("../components/mockups/warroom-alert-redesign/AlertSeverityStack.tsx"),
  "./components/mockups/warroom-alert-redesign/AlertTriage.tsx": () => import("../components/mockups/warroom-alert-redesign/AlertTriage.tsx"),
  "./components/mockups/warroom-alert-redesign/TriageClinicalProtocol.tsx": () => import("../components/mockups/warroom-alert-redesign/TriageClinicalProtocol.tsx"),
  "./components/mockups/warroom-alert-redesign/TriageQuietSentinel.tsx": () => import("../components/mockups/warroom-alert-redesign/TriageQuietSentinel.tsx"),
  "./components/mockups/warroom-alert-redesign/TriageWarmOperator.tsx": () => import("../components/mockups/warroom-alert-redesign/TriageWarmOperator.tsx"),
  "./components/mockups/warroom-feed-concepts/NarrativeThread.tsx": () => import("../components/mockups/warroom-feed-concepts/NarrativeThread.tsx"),
  "./components/mockups/warroom-feed-concepts/TheaterMap.tsx": () => import("../components/mockups/warroom-feed-concepts/TheaterMap.tsx"),
  "./components/mockups/warroom-feed-concepts/TimelineScatter.tsx": () => import("../components/mockups/warroom-feed-concepts/TimelineScatter.tsx"),
  "./components/mockups/warroom-feed-concepts/TriageQueue.tsx": () => import("../components/mockups/warroom-feed-concepts/TriageQueue.tsx"),
  "./components/mockups/warroom-feed-hierarchy/ClusterMap.tsx": () => import("../components/mockups/warroom-feed-hierarchy/ClusterMap.tsx"),
  "./components/mockups/warroom-feed-hierarchy/GravityFeed.tsx": () => import("../components/mockups/warroom-feed-hierarchy/GravityFeed.tsx"),
  "./components/mockups/warroom-feed-hierarchy/SplitChannel.tsx": () => import("../components/mockups/warroom-feed-hierarchy/SplitChannel.tsx"),
  "./components/mockups/warroom-redesign/Chronicle.tsx": () => import("../components/mockups/warroom-redesign/Chronicle.tsx"),
  "./components/mockups/warroom-redesign/MidnightLux.tsx": () => import("../components/mockups/warroom-redesign/MidnightLux.tsx"),
  "./components/mockups/warroom-redesign/Signal.tsx": () => import("../components/mockups/warroom-redesign/Signal.tsx"),
  "./components/mockups/warroom-redesign/TacticalHUD.tsx": () => import("../components/mockups/warroom-redesign/TacticalHUD.tsx"),
  "./components/mockups/warroom-redesign/TerminalFeed.tsx": () => import("../components/mockups/warroom-redesign/TerminalFeed.tsx"),
  "./components/mockups/warroom-redesign/ThreatHorizon.tsx": () => import("../components/mockups/warroom-redesign/ThreatHorizon.tsx"),
  "./components/mockups/warroom-vibes/FrostProtocol.tsx": () => import("../components/mockups/warroom-vibes/FrostProtocol.tsx"),
  "./components/mockups/warroom-vibes/NeonPulse.tsx": () => import("../components/mockups/warroom-vibes/NeonPulse.tsx"),
  "./components/mockups/warroom-vibes/WarmEmber.tsx": () => import("../components/mockups/warroom-vibes/WarmEmber.tsx")
};
